name: final_pos_herencia
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  connectivity_plus: ^6.1.4
  flutter_esc_pos_utils: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400 # Normal/Regular
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
          weight: 400 # Assuming Poppins-Italic is based on regular weight
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700 # Bold
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          style: italic
          weight: 700 # Assuming Poppins-BoldItalic is based on bold weight
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
